name: ciy_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  window_manager: ^0.2.7
  path_provider: ^2.1.2
  system_info: ^1.0.1
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4 
  equatable: ^2.0.0
  loading_animation_widget: ^1.2.0
  tar: ^1.0.3
  flex_color_scheme: ^7.3.1
  mutex: ^3.1.0
  http: ^1.2.0
  auto_exit_process: ^1.0.0+1
  pkce: ^1.1.0+1
  url_launcher: ^6.2.4
  window_to_front: ^0.0.3
  system_tray: ^2.0.3
  launch_at_startup: ^0.2.2
  package_info_plus: ^5.0.1
  windows_single_instance: ^1.0.1 
  flutter_secure_storage: ^9.0.0
  msix: ^3.16.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon_windows.png

msix_config:
  display_name: Cloud IY
  publisher_display_name: CloudIY™
  msix_version: 1.0.0.0
  logo_path: .\ciy_client\assets\app_icon_windows.png
  capabilities: internetClientServer, privateNetworkClientServer
