name: Build executable for windows amd64
run-name: ${{ github.actor }}
on: [ push ]
jobs:
  build-and-upload-package:
    timeout-minutes: 60
    runs-on: [self-hosted, Windows]
    env:
      PACKAGE_VERSION: 1.0.0
      PACKAGE_REGISTRY_URL: https://gitlab.com/api/v4/projects/54080196/packages/generic/ciy-ui
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          channel: stable
          version: '3.16.9

        

      - name: Flutter build
        run: flutter build windows --release

      - name: Copy DLLs
        run: |
          Copy-Item -Path "msvcp140.dll" -Destination "./build/windows/x64/runner/Release/"
          Copy-Item -Path "vcruntime140.dll" -Destination "./build/windows/x64/runner/Release/"
          Copy-Item -Path "vcruntime140_1.dll" -Destination "./build/windows/x64/runner/Release/"
  
      - name: Download virtualization
        run: |
          curl.exe -L -o ./Installers/qemu-w64-setup-20211215.exe https://qemu.weilnetz.de/w64/2021/qemu-w64-setup-20211215.exe

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Installers/windows_inno_setup_build.iss
          options: /O+

      - name: Upload to registry
        run: |
          curl.exe -X PUT --header "PRIVATE-TOKEN: glpat-3zqVQwKxwU_Qsvc_8fw8" -T ./Output/mysetup.exe $env:PACKAGE_REGISTRY_URL/$env:PACKAGE_VERSION/ciy-ui-$env:PACKAGE_VERSION-win-amd64.exe